<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 ANALISIS UNIVARIADO | bookdown-demo.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 ANALISIS UNIVARIADO | bookdown-demo.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 ANALISIS UNIVARIADO | bookdown-demo.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="IMPORTACIONES.html"/>
<link rel="next" href="analisis-bivariado.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="IMPORTACIONES.html"><a href="IMPORTACIONES.html"><i class="fa fa-check"></i><b>1</b> ANALISIS EXPLORATORIO DE DATOS</a>
<ul>
<li class="chapter" data-level="1.0.1" data-path="IMPORTACIONES.html"><a href="IMPORTACIONES.html#descripcion-del-problema"><i class="fa fa-check"></i><b>1.0.1</b> Descripcion del problema</a></li>
<li class="chapter" data-level="1.0.2" data-path="IMPORTACIONES.html"><a href="IMPORTACIONES.html#carga-de-datos"><i class="fa fa-check"></i><b>1.0.2</b> Carga de Datos</a></li>
<li class="chapter" data-level="1.0.3" data-path="IMPORTACIONES.html"><a href="IMPORTACIONES.html#exploracion-inicial"><i class="fa fa-check"></i><b>1.0.3</b> Exploracion inicial</a></li>
<li class="chapter" data-level="1.1" data-path="IMPORTACIONES.html"><a href="IMPORTACIONES.html#naturaleza-de-los-datos"><i class="fa fa-check"></i><b>1.1</b> Naturaleza de los datos</a></li>
<li class="chapter" data-level="1.2" data-path="IMPORTACIONES.html"><a href="IMPORTACIONES.html#caracteristicas-del-dataset"><i class="fa fa-check"></i><b>1.2</b> Caracteristicas del dataset</a></li>
<li class="chapter" data-level="1.3" data-path="IMPORTACIONES.html"><a href="IMPORTACIONES.html#revision-de-datos-faltantes"><i class="fa fa-check"></i><b>1.3</b> Revision de datos faltantes</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="analisis-univariado.html"><a href="analisis-univariado.html"><i class="fa fa-check"></i><b>2</b> ANALISIS UNIVARIADO</a>
<ul>
<li class="chapter" data-level="2.1" data-path="analisis-univariado.html"><a href="analisis-univariado.html#tasa-de-colocacion-total"><i class="fa fa-check"></i><b>2.1</b> Tasa De colocacion total</a></li>
<li class="chapter" data-level="2.2" data-path="analisis-univariado.html"><a href="analisis-univariado.html#creditos-de-consumo"><i class="fa fa-check"></i><b>2.2</b> Creditos De Consumo</a></li>
<li class="chapter" data-level="2.3" data-path="analisis-univariado.html"><a href="analisis-univariado.html#creditos-de-tesoreria"><i class="fa fa-check"></i><b>2.3</b> Creditos De Tesoreria</a></li>
<li class="chapter" data-level="2.4" data-path="analisis-univariado.html"><a href="analisis-univariado.html#creditos-ordinarios"><i class="fa fa-check"></i><b>2.4</b> Creditos Ordinarios</a></li>
<li class="chapter" data-level="2.5" data-path="analisis-univariado.html"><a href="analisis-univariado.html#creditos-preferenciales"><i class="fa fa-check"></i><b>2.5</b> Creditos Preferenciales</a></li>
<li class="chapter" data-level="2.6" data-path="analisis-univariado.html"><a href="analisis-univariado.html#tasa-de-colocacion-br"><i class="fa fa-check"></i><b>2.6</b> Tasa De Colocacion BR</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="analisis-bivariado.html"><a href="analisis-bivariado.html"><i class="fa fa-check"></i><b>3</b> ANALISIS BIVARIADO</a>
<ul>
<li class="chapter" data-level="3.1" data-path="analisis-bivariado.html"><a href="analisis-bivariado.html#math-example"><i class="fa fa-check"></i><b>3.1</b> math example</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analisis-univariado" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> ANALISIS UNIVARIADO<a href="analisis-univariado.html#analisis-univariado" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="tasa-de-colocacion-total" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Tasa De colocacion total<a href="analisis-univariado.html#tasa-de-colocacion-total" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="analisis-univariado.html#cb1-1" tabindex="-1"></a><span class="co"># Histograma con curva de densidad</span></span>
<span id="cb1-2"><a href="analisis-univariado.html#cb1-2" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> TasaColocacionTotal)) <span class="sc">+</span></span>
<span id="cb1-3"><a href="analisis-univariado.html#cb1-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), </span>
<span id="cb1-4"><a href="analisis-univariado.html#cb1-4" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb1-5"><a href="analisis-univariado.html#cb1-5" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;darkred&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-6"><a href="analisis-univariado.html#cb1-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-7"><a href="analisis-univariado.html#cb1-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Tasa De Colocacion Total&quot;</span>,</span>
<span id="cb1-8"><a href="analisis-univariado.html#cb1-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;TasaColocacionTotal(%)&quot;</span>,</span>
<span id="cb1-9"><a href="analisis-univariado.html#cb1-9" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span>,</span>
<span id="cb1-10"><a href="analisis-univariado.html#cb1-10" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb1-11"><a href="analisis-univariado.html#cb1-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-12"><a href="analisis-univariado.html#cb1-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb1-13"><a href="analisis-univariado.html#cb1-13" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb1-14"><a href="analisis-univariado.html#cb1-14" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb1-15"><a href="analisis-univariado.html#cb1-15" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb1-16"><a href="analisis-univariado.html#cb1-16" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb1-17"><a href="analisis-univariado.html#cb1-17" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="analisis-univariado.html#cb2-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="analisis-univariado.html#cb2-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb2-3"><a href="analisis-univariado.html#cb2-3" tabindex="-1"></a>    <span class="at">Media =</span> <span class="fu">mean</span>(TasaColocacionTotal, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-4"><a href="analisis-univariado.html#cb2-4" tabindex="-1"></a>    <span class="at">Mediana =</span> <span class="fu">median</span>(TasaColocacionTotal, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-5"><a href="analisis-univariado.html#cb2-5" tabindex="-1"></a>    <span class="at">Desviacion_Estandar =</span> <span class="fu">sd</span>(TasaColocacionTotal, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-6"><a href="analisis-univariado.html#cb2-6" tabindex="-1"></a>    <span class="at">Minimo =</span> <span class="fu">min</span>(TasaColocacionTotal, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-7"><a href="analisis-univariado.html#cb2-7" tabindex="-1"></a>    <span class="at">Maximo =</span> <span class="fu">max</span>(TasaColocacionTotal, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-8"><a href="analisis-univariado.html#cb2-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   Media Mediana Desviacion_Estandar Minimo Maximo
##   &lt;dbl&gt;   &lt;dbl&gt;               &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  14.7    12.8                6.66   8.16   53.5</code></pre>
<p>La variable Tesorería de Colocación Total, que será nuestro objetivo de predicción frente a la variable de tiempo, presenta un promedio de 14.7 y una mediana de 12.8, lo que evidencia una ligera asimetría positiva, ya que algunos valores altos elevan la media por encima de la mediana; la desviación estándar de 6.66 refleja una variabilidad moderada, mientras que el rango entre el mínimo de 8.16 y el máximo de 53.5 muestra tanto periodos de tasas relativamente bajas como episodios de tasas muy elevadas. En el contexto de la serie temporal mensual desde 1998, estos resultados sugieren que la tesorería de colocación total ha tenido un comportamiento con cierta estabilidad en torno a valores medios, pero con picos que responden a coyunturas macroeconómicas específicas, como crisis financieras, ajustes de política monetaria o presiones inflacionarias. Este patrón es fundamental para tu análisis exploratorio, ya que al ser la variable que se busca predecir, la combinación de estadísticas descriptivas y la representación gráfica en el tiempo permitirá identificar tendencias, ciclos y cambios estructurales, preparando el terreno para modelos predictivos que capturen la dinámica y sensibilidad del sistema financiero colombiano frente a variaciones en las condiciones de mercado.</p>
</div>
<div id="creditos-de-consumo" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Creditos De Consumo<a href="analisis-univariado.html#creditos-de-consumo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="analisis-univariado.html#cb4-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">y =</span> CreditosConsumo)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="analisis-univariado.html#cb4-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;darkseagreen&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb4-3"><a href="analisis-univariado.html#cb4-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb4-4"><a href="analisis-univariado.html#cb4-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución De Los Creditos De Consumo&quot;</span>,</span>
<span id="cb4-5"><a href="analisis-univariado.html#cb4-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;CreditosConsumo (%)&quot;</span>,</span>
<span id="cb4-6"><a href="analisis-univariado.html#cb4-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb4-7"><a href="analisis-univariado.html#cb4-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb4-8"><a href="analisis-univariado.html#cb4-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-9"><a href="analisis-univariado.html#cb4-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb4-10"><a href="analisis-univariado.html#cb4-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb4-11"><a href="analisis-univariado.html#cb4-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb4-12"><a href="analisis-univariado.html#cb4-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb4-13"><a href="analisis-univariado.html#cb4-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="analisis-univariado.html#cb5-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="analisis-univariado.html#cb5-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-3"><a href="analisis-univariado.html#cb5-3" tabindex="-1"></a>    <span class="at">Media =</span> <span class="fu">mean</span>(CreditosConsumo, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-4"><a href="analisis-univariado.html#cb5-4" tabindex="-1"></a>    <span class="at">Mediana =</span> <span class="fu">median</span>(CreditosConsumo, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-5"><a href="analisis-univariado.html#cb5-5" tabindex="-1"></a>    <span class="at">Desviacion_Estandar =</span> <span class="fu">sd</span>(CreditosConsumo, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-6"><a href="analisis-univariado.html#cb5-6" tabindex="-1"></a>    <span class="at">Minimo =</span> <span class="fu">min</span>(CreditosConsumo, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-7"><a href="analisis-univariado.html#cb5-7" tabindex="-1"></a>    <span class="at">Maximo =</span> <span class="fu">max</span>(CreditosConsumo, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-8"><a href="analisis-univariado.html#cb5-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   Media Mediana Desviacion_Estandar Minimo Maximo
##   &lt;dbl&gt;   &lt;dbl&gt;               &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  23.1    20.0                7.64   13.5   52.3</code></pre>
<p>La variable Créditos de Consumo presenta un promedio de 23.1 y una mediana de 20, lo que evidencia una distribución asimétrica positiva en la que algunos valores altos elevan la media; la desviación estándar de 7.64 refleja una variabilidad moderada, mientras que el rango entre el mínimo de 13.5 y el máximo de 52.3 confirma episodios de expansión y contracción del crédito a lo largo de más de dos décadas de datos mensuales del Banco de la República. En el contexto de una serie temporal, estas estadísticas sugieren que el crédito de consumo ha estado expuesto a ciclos de auge y restricción influenciados por factores macroeconómicos como tasas de interés, inflación y crisis financieras, lo que convierte su análisis en un punto de partida para identificar tendencias, cambios estructurales y relaciones con otras modalidades de crédito y tasas de colocación, preparando el terreno para modelos predictivos que capturen la dinámica y sensibilidad de este mercado en Colombia.</p>
</div>
<div id="creditos-de-tesoreria" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Creditos De Tesoreria<a href="analisis-univariado.html#creditos-de-tesoreria" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="analisis-univariado.html#cb7-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">y =</span> CreditosTesoreria)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="analisis-univariado.html#cb7-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;darkseagreen&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="analisis-univariado.html#cb7-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-4"><a href="analisis-univariado.html#cb7-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución De Los Creditos De Tesoreria&quot;</span>,</span>
<span id="cb7-5"><a href="analisis-univariado.html#cb7-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;CreditosTesoreria (%)&quot;</span>,</span>
<span id="cb7-6"><a href="analisis-univariado.html#cb7-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb7-7"><a href="analisis-univariado.html#cb7-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-8"><a href="analisis-univariado.html#cb7-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb7-9"><a href="analisis-univariado.html#cb7-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb7-10"><a href="analisis-univariado.html#cb7-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb7-11"><a href="analisis-univariado.html#cb7-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb7-12"><a href="analisis-univariado.html#cb7-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb7-13"><a href="analisis-univariado.html#cb7-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="analisis-univariado.html#cb8-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="analisis-univariado.html#cb8-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb8-3"><a href="analisis-univariado.html#cb8-3" tabindex="-1"></a>    <span class="at">Media =</span> <span class="fu">mean</span>(CreditosTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-4"><a href="analisis-univariado.html#cb8-4" tabindex="-1"></a>    <span class="at">Mediana =</span> <span class="fu">median</span>(CreditosTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-5"><a href="analisis-univariado.html#cb8-5" tabindex="-1"></a>    <span class="at">Desviacion_Estandar =</span> <span class="fu">sd</span>(CreditosTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-6"><a href="analisis-univariado.html#cb8-6" tabindex="-1"></a>    <span class="at">Minimo =</span> <span class="fu">min</span>(CreditosTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-7"><a href="analisis-univariado.html#cb8-7" tabindex="-1"></a>    <span class="at">Maximo =</span> <span class="fu">max</span>(CreditosTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-8"><a href="analisis-univariado.html#cb8-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   Media Mediana Desviacion_Estandar Minimo Maximo
##   &lt;dbl&gt;   &lt;dbl&gt;               &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  11.6    9.46                6.99   5.56   56.4</code></pre>
<p>La variable Créditos de Tesorería muestra un promedio de 11.6 y una mediana de 9.46, lo que indica nuevamente una distribución con ligera asimetría positiva, pues los valores altos elevan la media por encima de la mediana; la desviación estándar de 6.99 refleja una variabilidad moderada, aunque algo menor que la observada en los créditos de consumo, y el rango entre el mínimo de 5.56 y el máximo de 56.4 evidencia episodios de fuerte expansión en ciertos periodos frente a fases de baja colocación. En el contexto de la serie temporal mensual desde 1998, estos resultados sugieren que los créditos de tesorería han tenido un comportamiento más concentrado en valores bajos, pero con picos ocasionales que responden a condiciones macroeconómicas específicas, como necesidades de liquidez de las empresas o ajustes en las tasas de interés. Este patrón, menos estable que el de consumo pero con mayor dispersión relativa en los extremos, constituye un punto de partida para analizar la sensibilidad de esta modalidad frente a shocks financieros y su relación con otras formas de crédito, preparando el terreno para detectar ciclos, cambios estructurales y construir modelos predictivos que capturen su dinámica en el sistema financiero colombiano.</p>
</div>
<div id="creditos-ordinarios" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Creditos Ordinarios<a href="analisis-univariado.html#creditos-ordinarios" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="analisis-univariado.html#cb10-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">y =</span> CreditosOrdinarios)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="analisis-univariado.html#cb10-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;darkseagreen&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="analisis-univariado.html#cb10-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-4"><a href="analisis-univariado.html#cb10-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución Creditos Ordinarios&quot;</span>,</span>
<span id="cb10-5"><a href="analisis-univariado.html#cb10-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;CreditosOrdinarios (%)&quot;</span>,</span>
<span id="cb10-6"><a href="analisis-univariado.html#cb10-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb10-7"><a href="analisis-univariado.html#cb10-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb10-8"><a href="analisis-univariado.html#cb10-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb10-9"><a href="analisis-univariado.html#cb10-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb10-10"><a href="analisis-univariado.html#cb10-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb10-11"><a href="analisis-univariado.html#cb10-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb10-12"><a href="analisis-univariado.html#cb10-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb10-13"><a href="analisis-univariado.html#cb10-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="analisis-univariado.html#cb11-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="analisis-univariado.html#cb11-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb11-3"><a href="analisis-univariado.html#cb11-3" tabindex="-1"></a>    <span class="at">Media =</span> <span class="fu">mean</span>(CreditosOrdinarios, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-4"><a href="analisis-univariado.html#cb11-4" tabindex="-1"></a>    <span class="at">Mediana =</span> <span class="fu">median</span>(CreditosOrdinarios, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-5"><a href="analisis-univariado.html#cb11-5" tabindex="-1"></a>    <span class="at">Desviacion_Estandar =</span> <span class="fu">sd</span>(CreditosOrdinarios, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-6"><a href="analisis-univariado.html#cb11-6" tabindex="-1"></a>    <span class="at">Minimo =</span> <span class="fu">min</span>(CreditosOrdinarios, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-7"><a href="analisis-univariado.html#cb11-7" tabindex="-1"></a>    <span class="at">Maximo =</span> <span class="fu">max</span>(CreditosOrdinarios, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-8"><a href="analisis-univariado.html#cb11-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   Media Mediana Desviacion_Estandar Minimo Maximo
##   &lt;dbl&gt;   &lt;dbl&gt;               &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  15.6    14.3                7.17   6.89   49.5</code></pre>
<p>La variable Créditos Ordinarios presenta un promedio de 15.6 y una mediana de 14.3, lo que indica una distribución con ligera asimetría positiva, pues algunos valores altos elevan la media por encima de la mediana; la desviación estándar de 7.17 refleja una variabilidad moderada, mientras que el rango entre el mínimo de 6.89 y el máximo de 49.5 evidencia tanto periodos de baja colocación como episodios de expansión significativa. En el contexto de la serie temporal mensual desde 1998, estos resultados sugieren que los créditos ordinarios han mostrado un comportamiento relativamente estable en torno a valores medios, pero con picos ocasionales que responden a condiciones macroeconómicas o coyunturales específicas. Este patrón, menos extremo que el de tesorería pero con mayor dispersión que el de consumo, constituye un insumo clave para identificar tendencias, ciclos y posibles cambios estructurales en el sistema financiero colombiano, así como para preparar modelos predictivos que capturen su dinámica y sensibilidad frente a tasas de interés y otros factores económicos.</p>
</div>
<div id="creditos-preferenciales" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Creditos Preferenciales<a href="analisis-univariado.html#creditos-preferenciales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="analisis-univariado.html#cb13-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">y =</span> CreditosPreferenciales)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="analisis-univariado.html#cb13-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;darkseagreen&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="analisis-univariado.html#cb13-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-4"><a href="analisis-univariado.html#cb13-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución los Creditos Preferenciales&quot;</span>,</span>
<span id="cb13-5"><a href="analisis-univariado.html#cb13-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;CreditosPreferenciales (%)&quot;</span>,</span>
<span id="cb13-6"><a href="analisis-univariado.html#cb13-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb13-7"><a href="analisis-univariado.html#cb13-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb13-8"><a href="analisis-univariado.html#cb13-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-9"><a href="analisis-univariado.html#cb13-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb13-10"><a href="analisis-univariado.html#cb13-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb13-11"><a href="analisis-univariado.html#cb13-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb13-12"><a href="analisis-univariado.html#cb13-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb13-13"><a href="analisis-univariado.html#cb13-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="analisis-univariado.html#cb14-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="analisis-univariado.html#cb14-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-3"><a href="analisis-univariado.html#cb14-3" tabindex="-1"></a>    <span class="at">Media =</span> <span class="fu">mean</span>(CreditosPreferenciales, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-4"><a href="analisis-univariado.html#cb14-4" tabindex="-1"></a>    <span class="at">Mediana =</span> <span class="fu">median</span>(CreditosPreferenciales, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-5"><a href="analisis-univariado.html#cb14-5" tabindex="-1"></a>    <span class="at">Desviacion_Estandar =</span> <span class="fu">sd</span>(CreditosPreferenciales, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-6"><a href="analisis-univariado.html#cb14-6" tabindex="-1"></a>    <span class="at">Minimo =</span> <span class="fu">min</span>(CreditosPreferenciales, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-7"><a href="analisis-univariado.html#cb14-7" tabindex="-1"></a>    <span class="at">Maximo =</span> <span class="fu">max</span>(CreditosPreferenciales, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-8"><a href="analisis-univariado.html#cb14-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   Media Mediana Desviacion_Estandar Minimo Maximo
##   &lt;dbl&gt;   &lt;dbl&gt;               &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  12.0    10.6                7.23   4.34   49.6</code></pre>
<p>La variable Créditos Preferenciales presenta un promedio de 12.0 y una mediana de 10.6, lo que refleja una ligera asimetría positiva, ya que algunos valores altos elevan la media por encima de la mediana; la desviación estándar de 7.23 indica una variabilidad moderada, mientras que el rango entre el mínimo de 4.34 y el máximo de 49.6 evidencia tanto periodos de baja colocación como episodios de expansión significativa. En el contexto de la serie temporal mensual desde 1998, estos resultados sugieren que los créditos preferenciales han tenido un comportamiento más concentrado en valores bajos, pero con picos ocasionales que responden a condiciones macroeconómicas específicas o políticas de financiamiento dirigidas a ciertos sectores. Este patrón, con mayor dispersión relativa en los extremos, constituye un insumo clave para identificar tendencias, ciclos y posibles cambios estructurales en el sistema financiero colombiano, así como para preparar modelos predictivos que capturen su dinámica y sensibilidad frente a tasas de interés y otros factores económicos.</p>
</div>
<div id="tasa-de-colocacion-br" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Tasa De Colocacion BR<a href="analisis-univariado.html#tasa-de-colocacion-br" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="analisis-univariado.html#cb16-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">y =</span> TasaColocacionBR)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="analisis-univariado.html#cb16-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;darkseagreen&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="analisis-univariado.html#cb16-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-4"><a href="analisis-univariado.html#cb16-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución De La Tasa de Colocacion Br&quot;</span>,</span>
<span id="cb16-5"><a href="analisis-univariado.html#cb16-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;TasaColocationBR (%)&quot;</span>,</span>
<span id="cb16-6"><a href="analisis-univariado.html#cb16-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb16-7"><a href="analisis-univariado.html#cb16-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-8"><a href="analisis-univariado.html#cb16-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb16-9"><a href="analisis-univariado.html#cb16-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb16-10"><a href="analisis-univariado.html#cb16-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb16-11"><a href="analisis-univariado.html#cb16-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb16-12"><a href="analisis-univariado.html#cb16-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb16-13"><a href="analisis-univariado.html#cb16-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="analisis-univariado.html#cb17-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="analisis-univariado.html#cb17-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb17-3"><a href="analisis-univariado.html#cb17-3" tabindex="-1"></a>    <span class="at">Media =</span> <span class="fu">mean</span>(TasaColocacionBR, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-4"><a href="analisis-univariado.html#cb17-4" tabindex="-1"></a>    <span class="at">Mediana =</span> <span class="fu">median</span>(TasaColocacionBR, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-5"><a href="analisis-univariado.html#cb17-5" tabindex="-1"></a>    <span class="at">Desviacion_Estandar =</span> <span class="fu">sd</span>(TasaColocacionBR, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-6"><a href="analisis-univariado.html#cb17-6" tabindex="-1"></a>    <span class="at">Minimo =</span> <span class="fu">min</span>(TasaColocacionBR, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-7"><a href="analisis-univariado.html#cb17-7" tabindex="-1"></a>    <span class="at">Maximo =</span> <span class="fu">max</span>(TasaColocacionBR, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-8"><a href="analisis-univariado.html#cb17-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   Media Mediana Desviacion_Estandar Minimo Maximo
##   &lt;dbl&gt;   &lt;dbl&gt;               &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  15.5    14.3                6.85   8.20   50.5</code></pre>
<p>La variable Tasa de Colocación del Banco de la República presenta un promedio de 15.5 y una mediana de 14.3, lo que indica una ligera asimetría positiva, pues algunos valores altos elevan la media por encima de la mediana; la desviación estándar de 6.85 refleja una variabilidad moderada, mientras que el rango entre el mínimo de 8.20 y el máximo de 50.5 evidencia tanto periodos de tasas relativamente bajas como episodios de tasas muy elevadas. En el contexto de la serie temporal mensual desde 1998, estos resultados sugieren que la tasa de colocación ha tenido un comportamiento con cierta estabilidad en torno a valores medios, pero con picos que responden a coyunturas macroeconómicas específicas, como crisis financieras, ajustes de política monetaria o presiones inflacionarias. Este patrón es fundamental para el análisis exploratorio, ya que permite relacionar la evolución de las tasas con la dinámica de los distintos tipos de crédito, identificar ciclos y cambios estructurales en la política monetaria, y preparar modelos predictivos que capturen la sensibilidad del sistema financiero colombiano frente a variaciones en las condiciones de mercado.
## Tasa De Colocacion Sin Tesoreria</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="analisis-univariado.html#cb19-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">y =</span> TasaColocacionSinTesoreria)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="analisis-univariado.html#cb19-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;darkseagreen&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="analisis-univariado.html#cb19-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-4"><a href="analisis-univariado.html#cb19-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución De la Tasa De Colocacion Sin Tesoreria&quot;</span>,</span>
<span id="cb19-5"><a href="analisis-univariado.html#cb19-5" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;TasaColocacionSinTesoreria (%)&quot;</span>,</span>
<span id="cb19-6"><a href="analisis-univariado.html#cb19-6" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;n = 1,030 muestras&quot;</span></span>
<span id="cb19-7"><a href="analisis-univariado.html#cb19-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-8"><a href="analisis-univariado.html#cb19-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-9"><a href="analisis-univariado.html#cb19-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb19-10"><a href="analisis-univariado.html#cb19-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb19-11"><a href="analisis-univariado.html#cb19-11" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb19-12"><a href="analisis-univariado.html#cb19-12" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb19-13"><a href="analisis-univariado.html#cb19-13" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="analisis-univariado.html#cb20-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="analisis-univariado.html#cb20-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-3"><a href="analisis-univariado.html#cb20-3" tabindex="-1"></a>    <span class="at">Media =</span> <span class="fu">mean</span>(TasaColocacionSinTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-4"><a href="analisis-univariado.html#cb20-4" tabindex="-1"></a>    <span class="at">Mediana =</span> <span class="fu">median</span>(TasaColocacionSinTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-5"><a href="analisis-univariado.html#cb20-5" tabindex="-1"></a>    <span class="at">Desviacion_Estandar =</span> <span class="fu">sd</span>(TasaColocacionSinTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-6"><a href="analisis-univariado.html#cb20-6" tabindex="-1"></a>    <span class="at">Minimo =</span> <span class="fu">min</span>(TasaColocacionSinTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-7"><a href="analisis-univariado.html#cb20-7" tabindex="-1"></a>    <span class="at">Maximo =</span> <span class="fu">max</span>(TasaColocacionSinTesoreria, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb20-8"><a href="analisis-univariado.html#cb20-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   Media Mediana Desviacion_Estandar Minimo Maximo
##   &lt;dbl&gt;   &lt;dbl&gt;               &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  15.9    14.4                7.03   8.21   48.7</code></pre>
<p>La variable Tasa de Colocación sin Tesorería presenta un promedio de 15.9 y una mediana de 14.4, lo que refleja una ligera asimetría positiva, ya que algunos valores altos elevan la media por encima de la mediana; la desviación estándar de 7.03 indica una variabilidad moderada, mientras que el rango entre el mínimo de 8.21 y el máximo de 48.7 evidencia tanto periodos de tasas relativamente bajas como episodios de tasas elevadas. En el contexto de la serie temporal mensual desde 1998, estos resultados sugieren que la tasa de colocación sin tesorería ha mostrado un comportamiento relativamente estable en torno a valores medios, pero con picos que responden a coyunturas macroeconómicas específicas, como ajustes de política monetaria, presiones inflacionarias o crisis financieras. Este patrón constituye un insumo clave para el análisis exploratorio, ya que permite relacionar la evolución de las tasas con la dinámica de los distintos tipos de crédito, identificar ciclos y cambios estructurales en la política monetaria, y preparar modelos predictivos que capturen la sensibilidad del sistema financiero colombiano frente a variaciones en las condiciones de mercado.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="IMPORTACIONES.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analisis-bivariado.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/02-ANALISIS_UNIVARIADO.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
